replicaCount: 1

image:
  repository: ghcr.io/energinet-singularity/gis-provider/energinet-singularity/gis-provider
  pullPolicy: IfNotPresent
  tag: "1.1.1"

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: gis-provider-pvc
  podLabels:
    fm-gis-provider: "S1"
  selectorLabels:
    fm-gis-provider: "S1"
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: gis-fm-provider
                  operator: In
                  values:
                    - S1
            topologyKey: "kubernetes.io/hostname"

podLabels:
  gis-fm-provider: "S1"
selectorLabels:
  gis-fm-provider: "S1"
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: fm-gis-provider
              operator: In
              values:
                - S1
        topologyKey: "kubernetes.io/hostname"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []

EnvVars:
  API_PORT: 5000
  API_DB_NAME: "GIS_DATA"
  #GIS_FILENAME: ""
  #GIS_SHEET: ""
  #GIS_COLUMN_NAME: ""
  #LINE_NAME_REGEX: ""
  #ETS_COLUMN_DLR_ENABLED: ""
  #ETS_COLUMN_MRID: ""
  #ETS_FILENAME: ""
  #ETS_COLUMN_NAME: ""
  #MAP_COLUMN_GIS_NAME: ""
  #MAP_COLUMN_ETS_NAME: ""
  #MAP_FILENAME: ""
  #MAP_SHEET: ""
  #MOCK_DATA: ""

gisproviderDataVolume:
  accessMode: ReadWriteOnce
  size: 100M
  storageClass: standard
